#+TODO: INTERNET CONFIG PRACTICE | REM DONE WAIT

* rem
** Start Emacs with a specific init file:
   emacs -q -l ~/my-init-file.el
* Configuration Archive
** [3/3] Installed packages
- [X] session			 2.2.1		  installed	 use variables, registers and buffer places across sessions
- [X] yasnippet			 20121108.... installed	 Yet another snippet extension for Emacs. [source: github]
- [X] openwith			 20120531.... installed	 Open files with external programs [source: hg]
** [3/3] Basic
*** REM default editor
sudo update-alternatives --config editor
*** REM Open from terminal
emacs -nw
alias emacs='emacsclient -nw -a emacs24'
*** REM [3/3] Server/client
**** REM Configuration
- [X] (server-start) on .emacs
- [X] emacsclient -c -a emacs24
- [X] (remove-hook 'kill-buffer-query-functions 'server-kill-buffer-query-function) to avoid strange messages
**** REM From Ubuntu
- copiar /usr/share/applications/emacs.desktop y pegarlo modificado en 
  ~/.local/share/applications
- cambiar Exec
**** REM Maximized
maximized and fullboth
emacsclient -c -F "((fullscreen . fullboth))" -a emacs24 %F
emacsclient -c -F "((fullscreen . maximized))" -a emacs24 %F
** Blogs
http://www.masteringemacs.org
* [0/1] Usage
** PRACTICE learn
- C-h k (M-x describe-key) to show what command is bound to a key. For instance, on my machine save-buffers-kill-emacs isn't bound to anything, but C-h k C-x C-c tells me that C-x C-c is bound to save-buffers-kill-terminal. It will list all bindings for the command at the same time.
- C-h f (M-x describe-function) will show you the bindings for a command.
- C-h b (or M-x describe-bindings) will show you all bindings.
- C-h m (M-x describe-mode) is also handy to list bindings by mode.
** marks
- C-<SPC> set mark
- C-x C-x change mark and pointer
- C-<SPC> C-<SPC> transient mark just this time
- C-u C-<SPC> Move point to where the mark was, and restore the mark from the ring of former marks.
** Packages
1. M-x package-list-packages
2. Then...
  - r refresh the list from server.
  - i mark for installation.
  - u unmark.
  - d mark for deletion (removal of a installed package).
  - x for “execute” (start installation/remove of marked items).
** open sudo files
C-c C-f 
/sudo::/etc/apt/sources.list
** Code navigation
| keystroke   | action                        | Eclipse      | command                            |
|-------------+-------------------------------+--------------+------------------------------------|
| C-c , .     | go to definition              | <F3>         | semantic-ia-fast-jump              |
| C-c , P     | switch declaration/definition |              | semantic-analyze-proto-impl-toggle |
| C-c , h     | in include, go to file        |              | semantic-decoration-include-visit  |
| C-x C-space | go back                       | Alt + <left> | pop-global-mark                    |
* To read
http://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html#Init-File
http://www.gnu.org/software/emacs/manual/html_node/emacs/Hooks.html#Hooks
http://www.gnu.org/software/emacs/manual/html_node/emacs/Init-Examples.html#Init-Examples
* [0/1] Office
** org-mode
** INTERNET [1/3] spellchecking
*** REM flyspell-mode
http://emacs-fu.blogspot.com.es/2009/12/automatically-checking-your-spelling.html
**** comments on programs
- M-x flyspell-prog-mode
**** Spanish
- M-x ispell-change-dictionary
- castellano
- /usr/lib/aspell/castellano
- sudo apt-get install aspell-es
*** INTERNET autolang-mode
http://www.emacswiki.org/emacs/AutoLangMode
*** INTERNET gramar and style
http://www.gnu.org/software/diction/diction.html
* [2/4] Internet
** REM (IRC) Quassel -> ERC
http://freenode.net/faq.shtml#nicksetup
*** links
http://www.emacswiki.org/ERC
http://www.emacswiki.org/emacs/InternetRelayChat
http://www.mwolson.org/static/doc/erc.html
http://www.emacswiki.org/emacs/ErcIntroduction
http://www.irchelp.org/irchelp/irctutorial.html
http://www.irchelp.org/irchelp/irctutorial.html#cmds
*** Connect and disconnect
http://www.emacswiki.org/emacs/ErcBasics
- M-x erc
  IRC server: irc.freenode.net
  IRC port: 6667
  Nickname: (type a nickname)
  Password: (none)
- M-x irc // C-c i
- /JOIN #freicoin – join channel #freicoin
- /PART – leave the current channel
- /QUIT msg – disconnect and leave message msg for all to see
*** More
http://www.irchelp.org/irchelp/irctutorial.html
- /NAMES #channel-name
- /WHOIS nickname
- /HELP
** INTERNET web gmail -> gnus/fetch
** WAIT opera -> emacs / better use conkeror
http://emacs-fu.blogspot.com.es/2010/12/conkeror-web-browsing-emacs-way.html
http://conkeror.org/
http://superuser.com/questions/434228/installing-conkeror-on-ubuntu-12-04
* PRACTICE [1/3] Nautilus -> Dired
** REM Hidden files
'M-o'
http://www.emacswiki.org/emacs/DiredOmitMode
** CONFIG Bookmarks
http://www.emacswiki.org/emacs/BookmarkPlus#BookmarkBasics
http://emacswiki.org/emacs/BookMarks
** INTERNET Open with...
* [1/4] Eclipse -> Emacs
** REM Build project
http://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation.html
- freicoin: make -f makefile.unix
- M-x compile
   Run a compiler asynchronously under Emacs, with error messages going to the *compilation* buffer. 
- M-x recompile
   Invoke a compiler with the same command as in the last invocation of M-x compile. 
- M-x kill-compilation
   Kill the running compilation subprocess.
** Navigation
*** CONFIG F3 -> ctags
ctags -e -R .
*** INTERNET C-g -> cscope
http://stackoverflow.com/questions/934233/cscope-or-ctags-why-choose-one-over-the-other
** CONFIG Refactor
http://www.masteringemacs.org/articles/2012/10/02/iedit-interactive-multi-occurrence-editing-in-your-buffer/
** INTERNET Debug
** INTERNET Git
** Packed solutions
*** EDE ??
http://www.gnu.org/software/emacs/manual/html_node/ede/index.html
*** emacs-IDE ??
http://emacs-ide.tuxfamily.org/
*** CEDET ?
http://www.emacswiki.org/CollectionOfEmacsDevelopmentEnvironmentTools
http://cxwangyi.wordpress.com/2010/08/21/using-cedet-with-emacs/
http://alexott.net/en/writings/emacs-devenv/EmacsCedet.html
* CEDET
http://cedet.sourceforge.net/
http://www.emacswiki.org/CollectionOfEmacsDevelopmentEnvironmentTools
http://cedet.sourceforge.net/setup.shtml
http://alexott.net/en/writings/emacs-devenv/EmacsCedet.html
http://lwn.net/Articles/502119/
http://cxwangyi.wordpress.com/2010/08/21/using-cedet-with-emacs/
** semantics
http://www.gnu.org/software/emacs/manual/html_node/emacs/Semantic.html
http://www.gnu.org/software/emacs/manual/html_node/semantic/index.html#Top
http://www.gnu.org/software/emacs/manual/html_node/semantic/Using-Semantic.html#Using-Semantic
** EDE
global-ede-mode
(global-ede-mode 1)
** ECB
http://ecb.sourceforge.net/
http://stackoverflow.com/questions/8833235/install-ecb-with-emacs-starter-kit-in-emacs-24
** smart completion
http://cedet.sourceforge.net/intellisense.shtml
* PRACTICE ediff
emacs --eval "(ediff-files \"file_1\" \"file_2\")"
emacsclient -diff todoNPA.org todoIndra.org
emacsclient --eval "(ediff-files \"todoNPA.org\" \"todoIndra.org\")"

diff todoNPA.org todoIndra.org

emacsclient -diff aaa.txt bbb.txt
emacsclient --eval "(ediff-files \"aaa.txt\" \"bbb.txt\")"

??
emacsclient --eval "(emerge-files \"aaa.txt\" \"bbb.txt\" \"ccc.txt\")"


